export const categories = [
  { cat: 'AT', name: 'Assortments' },
  { cat: 'BR', name: 'Bottle Rocket' },
  { cat: 'CF', name: 'Confetti' },
  { cat: 'FE', name: 'Fuses' },
  { cat: 'FG', name: 'Fountains (1000g)' },
  { cat: 'FN', name: 'Fountains' },
  { cat: 'FR', name: 'Firecrackers' },
  { cat: 'FS', name: 'Firing Systems' },
  { cat: 'GM', name: 'Multi-Shot (500g)' },
  { cat: 'ME', name: 'Missiles' },
  { cat: 'MS', name: 'Multi-Shot (200g)' },
  { cat: 'MX', name: 'Multi-Shot (350g)' },
  { cat: 'NF', name: 'Novelties (Flying)' },
  { cat: 'NV', name: 'Novelties (Ground)' },
  { cat: 'PC', name: 'Parachutes' },
  { cat: 'PK', name: 'Punks' },
  { cat: 'RC', name: 'Roman Candles' },
  { cat: 'RL', name: 'Artillery Shells' },
  { cat: 'SK', name: 'Smoke Bombs' },
  { cat: 'SM', name: 'Saturn Missiles' },
  { cat: 'SN', name: 'Snappers' },
  { cat: 'SP', name: 'Sparklers' },
  { cat: 'SR', name: 'Stick Rockets' },
  { cat: 'TB', name: 'Tubes & NOABs' },
]

export const groupings = [
  { group: 'multi', name: 'Multi-Shot', categories: [ 'MS', 'MX', 'GM', 'TB' ]},
  { group: 'fountain', name: 'Fountains', categories: [ 'FG', 'FN' ]},
  { group: 'rocket', name: 'Rockets', categories: [ 'BR', 'ME', 'RC', 'SM', 'SR' ]},
  { group: 'novelty', name: 'Novelties', categories: [ 'CF', 'FR', 'NF', 'NV', 'PC', 'SK', 'SN', 'SP'  ]},
  { group: 'systems', name: 'Firing Systems', categories: [ 'FS', 'FE' ]},
  { group: 'artillery', name: 'Artillery Shells', categories: [ 'RL' ]},
]
