const videos = [
  { sku: 'AT134',	name: 'Pyro Station Assortment' },
  { sku: 'AT138',	name: 'Power Play Assortment' },
  { sku: 'AT142',	name: 'Johnny Bs Pyro Set' },
  { sku: 'AT143',	name: 'Johnny Bs Pyro Set (S&S)' },
  { sku: 'AT145',	name: 'Pyro Pail (S&S)' },
  { sku: 'AT248',	name: 'Flying Space' },
  { sku: 'AT251',	name: 'Lil Goodie Bag (S&S)' },
  { sku: 'AT283',	name: 'Big Mudder Trucker (S&S)' },
  { sku: 'AT286',	name: 'Red White & Blue Assortment (Party Asst 2)' },
  { sku: 'AT287',	name: 'Kids Fun Assortment (S&S)' },
  { sku: 'BR101',	name: 'Moon Travelers with Report' },
  { sku: 'BR103',	name: 'Whistling Moon Travelers With Report' },
  { sku: 'CF127',	name: 'Party Popper' },
  { sku: 'FE111A', name: 'Fuse Connex (bulk)' },
  { sku: 'FE124-P',	name: 'Medium Cake Fuse (3mm) 16 to 18 sec/ft (1 roll)' },
  { sku: 'FG123',	name: 'Whack A Mole' },
  { sku: 'FG131',	name: 'Fantasy Reality' },
  { sku: 'FG133',	name: 'Eruption' },
  { sku: 'FG134',	name: 'Closed Caption' },
  { sku: 'FN107',	name: 'Boom Barrel' },
  { sku: 'FN120',	name: 'Machine Gun Kelly' },
  { sku: 'FN127',	name: 'America Forever' },
  { sku: 'FN131',	name: 'After the Hunt' },
  { sku: 'FN140',	name: 'Mount Taal - 6" Cone' },
  { sku: 'FN142',	name: 'Star Factor' },
  { sku: 'FN143',	name: 'Blaze' },
  { sku: 'FN146',	name: 'Dueling Pistol' },
  { sku: 'FN147',	name: 'Cobra' },
  { sku: 'FN150',	name: 'Watermelon Ninja' },
  { sku: 'FN155',	name: 'Dagger' },
  { sku: 'FN164',	name: 'Loot Box' },
  { sku: 'FN365',	name: 'Snow Cone' },
  { sku: 'FN385',	name: 'Koi Pond' },
  { sku: 'FN396',	name: 'Snow Cone, Jr.' },
  { sku: 'FN430',	name: 'Smash Hit' },
  { sku: 'FN463',	name: 'Grand Cannon' },
  { sku: 'FN466',	name: 'Tiny Tug' },
  { sku: 'FN475',	name: 'Neon Nights' },
  { sku: 'FN480',	name: 'Sawworks' },
  { sku: 'FR280',	name: 'Cherry Bomb Firecrackers 16s' },
  { sku: 'FR285',	name: 'Cherry Bomb Firecrackers 200s' },
  { sku: 'FR286',	name: 'Cherry Bomb Firecrackers 1,000s' },
  { sku: 'FS304',	name: 'Ignite Lite - Retail Display Bundle' },
  { sku: 'FS305',	name: 'IGNITE Clip-on Igniters (20 pack)' },
  { sku: 'GM100',	name: 'Da Big Bomb Box' },
  { sku: 'GM1018', name: 'Hardcore Cycles' },
  { sku: 'GM108',	name: 'Printer Malfunction' },
  { sku: 'GM116',	name: 'Backyard King' },
  { sku: 'GM119',	name: 'American Glory' },
  { sku: 'GM121',	name: 'Saturday Night Special' },
  { sku: 'GM136',	name: 'Viva Mexico' },
  { sku: 'GM141',	name: 'Black Dragon' },
  { sku: 'GM151',	name: 'Jurassic Pork' },
  { sku: 'GM152',	name: 'Shock the Monkey' },
  { sku: 'GM180',	name: '1500-Gram Finale' },
  { sku: 'GM180B', name: 'All-American 1000-Gram Finale' },
  { sku: 'GM194',	name: 'America (est 1776)' },
  { sku: 'GM199',	name: 'Brocade Blues' },
  { sku: 'GM272',	name: 'Flip Flop Fly' },
  { sku: 'GM497',	name: 'High Falutin' },
  { sku: 'GM498',	name: 'Hit the Road Jack' },
  { sku: 'GM634B', name: 'Rainbow' },
  { sku: 'GM638',	name: 'Sweet Spot' },
  { sku: 'GM641',	name: 'Crack of Dawn' },
  { sku: 'GM750',	name: 'Monster Bucks' },
  { sku: 'GM751',	name: 'Whistling Wings' },
  { sku: 'GM866',	name: 'Bull Market' },
  { sku: 'GM891',	name: 'Highway Robbery' },
  { sku: 'GM983',	name: 'Carolina Reaper' },
  { sku: 'ME100',	name: 'Sky Bacon Missile - 12"' },
  { sku: 'ME101',	name: 'X-Wing Missile - 6"' },
  { sku: 'MS108',	name: 'Twitter Glitter' },
  { sku: 'MS113',	name: 'Garden in Spring' },
  { sku: 'MS121',	name: 'Color Pearl 96s' },
  { sku: 'MS138',	name: 'Bacon Trek' },
  { sku: 'MS142',	name: 'Happy 49 shots' },
  { sku: 'MS150',	name: 'Patriotic American' },
  { sku: 'MS151',	name: 'Gold Chainz' },
  { sku: 'MS153',	name: 'TorchPig' },
  { sku: 'MS310',	name: 'Feats of Strength - Assorted' },
  { sku: 'MS428',	name: 'Suspended Animation' },
  { sku: 'MS469B', name: 'Daytime Reveal - Blue' },
  { sku: 'MS469P', name: 'Daytime Reveal - Pink' },
  { sku: 'MS562',	name: 'Pheasant Hunt' },
  { sku: 'MS570',	name: 'Pretty in Pink' },
  { sku: 'MS619',	name: 'Quantum Zoo (Asst)' },
  { sku: 'MS635',	name: 'Money Box' },
  { sku: 'MS637',	name: 'Uncle Ham' },
  { sku: 'MS639',	name: 'Reel American' },
  { sku: 'MX100',	name: 'Attack' },
  { sku: 'MX101',	name: 'Home On The Range' },
  { sku: 'MX157',	name: 'Striker Serpent' },
  { sku: 'MX158',	name: 'Greenheads' },
  { sku: 'MX159',	name: 'Wild Boar' },
  { sku: 'MX161',	name: 'Game Over' },
  { sku: 'MX165',	name: 'Ultimate Celebration' },
  { sku: 'MX173',	name: 'Gigablaster' },
  { sku: 'MX182',	name: 'Blue Line' },
  { sku: 'MX186',	name: 'Game Night (Assorted)' },
  { sku: 'NF107',	name: 'Green Wasp' },
  { sku: 'NF112',	name: 'Ladybugs (60/3)' },
  { sku: 'NF210',	name: 'Jet Fighter Trio' },
  { sku: 'NF211',	name: 'Air Force Fleet' },
  { sku: 'NF219',	name: 'Pigs Can Fly' },
  { sku: 'NV102',	name: 'Naughty Dog' },
  { sku: 'NV108',	name: 'Jumbo Crackling Ball' },
  { sku: 'NV112',	name: 'Tank w/ Report' },
  { sku: 'NV123A', name: 'Booby Trap' },
  { sku: 'NV131',	name: 'Assorted Snake Bag' },
  { sku: 'NV132',	name: 'Snakes out of the Cave' },
  { sku: 'NV133',	name: 'Premium Ground Bloom Flower' },
  { sku: 'NV161',	name: 'Sky Bacon Spinners' },
  { sku: 'NV180A', name: 'Fart Bags' },
  { sku: 'NV182',	name: 'Stink Bombs' },
  { sku: 'NV209A', name: 'Climbing Panda' },
  { sku: 'NV293',	name: 'Normandy Landing Craft' },
  { sku: 'NV316',	name: 'Spinning Firefly' },
  { sku: 'NV319',	name: 'Half Ton' },
  { sku: 'NV340',	name: 'Screeching Eagle' },
  { sku: 'NV353',	name: 'Frog' },
  { sku: 'PC146',	name: 'Princess Skydive' },
  { sku: 'PC147',	name: 'Patriotic Skydive' },
  { sku: 'PC149',	name: 'Giant Parachute 40-inch' },
  { sku: 'PK100A', name: 'Jumbo Punks 19in. (400/4)' },
  { sku: 'PR128',	name: 'Sky Bacon Table Bunting - 150 feet' },
  { sku: 'PR173',	name: 'Large Shopping Bags' },
  { sku: 'PR191',	name: 'Pennant String - 20 Ft' },
  { sku: 'PR192',	name: 'Feather Flag' },
  { sku: 'RC101',	name: 'Bacon Bit Barrage' },
  { sku: 'RC108',	name: 'Crazy Aces' },
  { sku: 'RC123',	name: 'Super Gatling Blaster' },
  { sku: 'RC233',	name: 'Roman Candle Poly Pack' },
  { sku: 'RC265',	name: 'Assorted Mini Candles' },
  { sku: 'RL105A', name: 'Premium Festival Balls 1" (Canisters)' },
  { sku: 'RL114',	name: 'One-Inch Wonder' },
  { sku: 'RL133',	name: '6" Ring Master' },
  { sku: 'RL240',	name: '5" Hellcat Cans (60-gram Canisters)' },
  { sku: 'RL240B', name: '5" Hellcat Cans - 60-Gram Canister Shells' },
  { sku: 'RL292',	name: 'Close Combat' },
  { sku: 'RL335',	name: '24 Turbo Charged - 1.5" Canister Shells' },
  { sku: 'RL337',	name: 'Double Dragon - 6" Double-Break Canister' },
  { sku: 'RL350',	name: 'Titanium Willow Shells - 5" Canister' },
  { sku: 'RL360',	name: 'Festival Balls - 1.5" Ball Shells' },
  { sku: 'SK109',	name: 'Neon Smoke Balls Clay' },
  { sku: 'SK111',	name: 'Jumbo Color Smoke Balls' },
  { sku: 'SK115B', name: 'Color Military Smoke' },
  { sku: 'SK134',	name: 'Color Smoke Grenades' },
  { sku: 'SK143',	name: 'Worlds Largest Smoke Ball' },
  { sku: 'SK148',	name: 'Sword of Daylight' },
  { sku: 'SM104',	name: 'Jumbo Saturn Missiles' },
  { sku: 'SM128',	name: 'Flag Missile Battery' },
  { sku: 'SM150',	name: 'Saturn Missile Battery' },
  { sku: 'SM167',	name: 'Neon Saturn Missiles' },
  { sku: 'SN109',	name: 'Americas Best Snappers (RWB)' },
  { sku: 'SN115',	name: 'Bacon Snaps (Adult Snaps)' },
  { sku: 'SN116',	name: 'Poppin Snaps' },
  { sku: 'SP008BC',	name: '#8 Bamboo Sparklers - Color' },
  { sku: 'SP116T', name: 'Morning Glory - 24in' },
  { sku: 'SP192',	name: 'Ten-Inch Sparklers (Wire)' },
  { sku: 'SR122',	name: 'Maximum Altitude - TX Legal' },
  { sku: 'SR216',	name: 'Skybolt - TX Legal' },
  { sku: 'SR224',	name: 'Giant Texas Pop Rocket - TX Legal' },
  { sku: 'TB211',	name: 'Addicted to Loud' },
  { sku: 'TB215',	name: 'Khaotic KaBoom' },
  { sku: 'TB237',	name: 'Whacky Tobacky' },
  { sku: 'TB247',	name: 'Unstoppable' },
  { sku: 'TB248',	name: 'Monstrous Brocade Ring' },
  { sku: 'TB261',	name: 'Immortal' },
]

export default videos;
